name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e6d78eb200e4204a854560c80ff0767112010152c227805cf5be096f9c597ea"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
