name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4842aea5998088f5f5c151b038921e10671ebfc23e9bfe07fd132159365b45a7"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
