name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fb95351b92a1f185ec4336424b2c0bbed76b81bf3411835e2a22b61fabd4314"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
