name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffcd2bf9b7f95b1f4ff3df2da52c232086dde28d2ff8aee6f444040d70c07beb"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
