name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9179f805c8fd70ccbb8267ba85e3cd5ca5525c0ec9911e55190596a0bd9819f"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
