name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93355e92182dd244d14f2f731ea49bcb41d1474bbe4ec5801edd1d42c1e990ed"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
