name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5540781687ead7ecd23d411da8cd8aa05808d04f482b9f9f5aad2b2894fe4762"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
