name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40c62f445674bfe251a50a30f37433cd8512fef1776b298439581af5164d2ac5"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
