name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52fb418d109b3626ae1207f72208bb50949e6ff947f369ceb7e2ebdfc863d072"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
