name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83fa33c173ef04448a71d35d80473da9a08cb7ab5064a5ea852e8944467b6ee0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
