name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47f15b9b0bc030fd6ee602a83cc579814cf529a94c201d0a93387b00e34e3675"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
