name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19f13d39ae76f7bded9c55a4ffc0d49227dbf8f3a817303a10e4c1a4520b922c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
