name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac84eff3da6dba204e609b54d17e9b46cfff7e39a80f7d9c26867ac541521499"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
