name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fe852eb753a47bdb7d7790ce3ea74e99b9babf386c8f474a9764aa5077555c0"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
