name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38b281c2dfd45e45f112b8d3572eab3f38feb6ad7865ea37230c2c854372d3d6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
