name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec9a851b7bbc62f417e5f57ad9cb6de994cbc410b62cef88845a7404ca60a1cc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
