name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c08f78890ee7cf9d2e69d82b179dd7efb0eadbf1e8874dcd147c0e4dbec934e9"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
