name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f24abc6ba05636cbbe7500a44f168dc740efa19ff28217b7571725ba38a1d70b"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
