name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd59a9f716f622cab1452f5a7943457c43d2508908788bbe78a0669e6f8efc4f"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
