name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbe13c96f0c112fa1f82ebefff223cb4a689556b311eb401c1e729743129fdb0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
