name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc97243cc2d660160a7641cb1bde209721d0fb41e4d13fbe1a01608098a778a2"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
