name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf43a3fe26ce578bd1bcf56a3ba40be7c1ea5d8a7e0cc42db0a7ca2acd62a901"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
