name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8b14bb66930feafdafd30745e4128cc1d6c17fddfc0274b6836338b981cca06"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
