name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d22eb3aae352e33be9a3932d2675a8f16c4a7c016c4f5e729bd35ef2ba436c47"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
