name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cecd4e22e71b1669a0661c6aa178c982badb48a0eba66cca04c958362ecf4dc5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
