name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45727857b9f64f07efc9ae70bf06bd68479f93da40866b7b405a7583ed60cd17"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
