name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a339ad71c1b2e0cf3a2af992ebfab8e9b9beec64f7fd3bdfcc83a9f73110cc7e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
