name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "236056362b61e921734fd281fabb93ff7fd80cd9168dfafe8761920868f4cb86"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
