name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f43e7410ef573adfd2a18e0022787244a222c3372857f266bce79764d234452d"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
