name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c080b9a70f1b0139f0737d98dbe39e878a90bda913353ab3fe4e0794a68ef75e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
