name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0f204dc67d229d9a2df8f699c35ad2fe7a355878b64659bb5ebe9991ca518b8"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
