name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "100f72e1e00110d7def1c5029eef451facba3e8e144da805fdede9b8b8fb8e46"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
