name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c15ca32412256fad0d52b979cc4d24197be88092c3dd30859177ba02e50c00b5"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
