name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cb012003be060441eb3ae098541c4e39b6f6a6f21da67543eb00833757c4e5d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
