name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a03f4203098ff39cb0e62adf586cd3e4e4efcf40f3d730a21da67b26dbd46e1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
