name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b2eb758bb49bbcc92bd08e3f1f72f456bd476dbcf840704c53956c6ad69c490"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
