name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f35bb6c4dd65eb0c7ba9c602fc9d658882693f0bddfe7667522c962d823eb763"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
