name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80720fe8e52d764898eb5d7defda6468015bff9fdf2b2f955bfddc26620be175"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
