name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce7cbf3b4748b595947f0c83a90185ddd23d7eba0151431d577f886855a2ebb2"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
