name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a61d08e0e7f64a089168c4afa029bb0dd1028f7aa382ff71cfbc58d6d7669b03"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
