name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c59871968816f7b43fab9429ae622d0a8a8d6f3c0402bb3e82e94453d7d09ac"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
