name = "JSPCD5"
author = "Codion"
version = "0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34132fbec46a1c89a933fb4568d174eec59e1cd7ddf788c99edee9d390cb8d5c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
