keepHatOnDeath = false
seasonalBagChance = 20
enableMobLoot = true
enableChestLoot = true
allowHatInHelmetSlot = true
chestNoneWeight = 600
chestCommonWeight = 20
chestUncommonWeight = 15
chestRareWeight = 10
chestEpicWeight = 5
entityNoneWeight = 600
entityCommonWeight = 20
entityUncommonWeight = 15
entityRareWeight = 10
entityEpicWeight = 5
