enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
farmersdelight = true
seasonsextras = true
forgottengraves = true
sihywtcamd = true
extendedcopper = true
progression_reborn = true
urkazmoontools = true
immersive_portals = true
ecologics = true
friendsandfoes = true
twigs = true
natures_spirit = true
legacies_and_legends = true
sprout = true
enhancedcelestials = true
blossom = true
comforts = true
chalk = true
bitsandchisels = true
duckling = true
snowyspirit = true
nethersdelight = true
sleep_tight = true
brickvariety = true
fastpaintings = true
additionaladditions = true
lunade = true
archeologyplus = true
advancementframes = true
wilderwild = true
snowrealmagic = true
charm = true
end_reborn = true
gardens_of_the_dead = true
betterlily = true
customportalapi = true
pearfection = true
supplementaries = true
mo_glass = true
bedspreads = true
quartzelv = true
promenade = true
endrem = true
biomemakeover = true
windchimes = true
echochest = true
missingwilds = true
snuffles = true
modern_glass_doors = true
davespotioneering = true
just_end_anchor = true
philipsruins = true
endgame_reborn = true
minecraft = true
animal_feeding_trough = true
fwaystones = true
gipples_galore = true
snifferplus = true
abstoneedition = true
endermanoverhaul = true
toughglass = true
creeperoverhaul = true
decorative_blocks = true
sculk_depths = true
bedrockify = true
muffins_slimegolem = true
abverticaledition = true
blockus = true
