debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[[key_bindings]]
keys = []
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings]]
name = "key.plasmovoice.general.disable_voice"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 78
type = "KEYSYM"

[[key_bindings]]
keys = []
name = "key.plasmovoice.general.action"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings]]
name = "key.plasmovoice.proximity.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 72
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.whisper.ptt"
any_context = true
category = "hidden"

[[key_bindings.keys]]
code = 340
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.whisper.toggle"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 72
type = "KEYSYM"



[voice]
disabled = false
microphone_disabled = false
activation_threshold = -45.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.2
noise_suppression = true
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = true
hrtf = true
stereo_capture = false

[voice.volumes.proximity]
volume = 1.0
[voice.volumes.whisper]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 215
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 2
show_static_source_icons = true
overlay_enabled = false
overlay_position = "TOP_RIGHT"
overlay_style = "SKIN"

[overlay.source_states]
proximity = "OFF"
whisper = "OFF"
