# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				furnace = true
				dropper = true
				daylight_detector = true
				jukebox = true
				sign = true
				brewing_stand = true
				sculk_sensor = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				sculk_shrieker = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				sculk_catalyst = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				trapped_chest = true
				blast_furnace = true
				hanging_sign = true
				calibrated_sculk_sensor = true
				chiseled_bookshelf = true
				brushable_block = true
				decorated_pot = true

			[light_sources.settings.block_entities.farmersdelight]
				basket = true
				canvas_sign = true
				stove = true
				cutting_board = true
				skillet = true
				cabinet = true
				cooking_pot = true

			[light_sources.settings.block_entities.easyanvils]
				anvil = true

			[light_sources.settings.block_entities.animal_feeding_trough]
				feeding_trough = true

			[light_sources.settings.block_entities.snowyspirit]
				glow_lights = true

			[light_sources.settings.block_entities.sleep_tight]
				infested_bed = true
				hammock = true

			[light_sources.settings.block_entities.seasonsextras]
				greenhouse_glass = true
				air_conditioning = true
				season_calendar = true
				season_detector = true

			[light_sources.settings.block_entities.nethersdelight]
				nether_brick_smoker = true
				blackstone_blast_furnace = true
				blackstone_furnace = true
				blackstone_stove = true

			[light_sources.settings.block_entities.visualworkbench]
				crafting_table = true

			[light_sources.settings.block_entities.lunade]
				copper_fitting = true
				copper_pipe = true

			[light_sources.settings.block_entities.blockus]
				wooden_barrel = true

			[light_sources.settings.block_entities.wondrouswilds]
				tree_hollow = true
				nest_box = true

			[light_sources.settings.block_entities.yigd]
				grave_block_entity = true

			[light_sources.settings.block_entities.adventurez]
				dragon_egg_entity = true
				stone_holder_entity = true
				piglin_flag_entity = true
				shadow_chest_entity = true

			[light_sources.settings.block_entities.immersive_weathering]
				icicle = true

			[light_sources.settings.block_entities.ecologics]
				pot = true
				sign = true

			[light_sources.settings.block_entities.edenring]
				eden_portal = true

			[light_sources.settings.block_entities.comforts]
				sleeping_bag = true
				hammock = true

			[light_sources.settings.block_entities.campanion]
				lawn_chair = true
				rope_bridge_planks = true
				rope_bridge_post = true
				tent_part = true

			[light_sources.settings.block_entities.sprout]
				bounce_bug_block_entity = true
				flower_box = true
				butter_fly_block_entity = true

			[light_sources.settings.block_entities.bedspreads]
				decorated_bed = true

			[light_sources.settings.block_entities.chimes]
				iron_wind_chime_block_entity = true
				crystal_wind_chime_block_entity = true
				copper_wind_chime_block_entity = true
				bamboo_wind_chime_block_entity = true

			[light_sources.settings.block_entities.cave_enhancements]
				spectacle_candle = true
				redstone_receiver = true
				rose_quartz_chimes = true

			[light_sources.settings.block_entities.charm]
				kiln = true
				totem_block = true
				variant_chest = true
				bookcase = true
				trapped_chest = true

			[light_sources.settings.block_entities.paradise_lost]
				orange = true
				wisteria = true
				skyroot = true
				food_bowl = true
				incubator = true
				crystal = true
				golden_oak = true
				cherine_campfire = true

			[light_sources.settings.block_entities.bclib]
				barrel = true
				chest = true
				furnace = true
				sign = true

			[light_sources.settings.block_entities.oxidized]
				copper_kiln_block_entity = true

			[light_sources.settings.block_entities.chiselsandbits]
				chiseled_printer = true
				bit_storage = true
				chiseled = true

			[light_sources.settings.block_entities.supplementaries]
				pedestal = true
				flag = true
				hanging_sign_oak = true
				trapped_present = true
				notice_board = true
				ceiling_banner = true
				present = true
				sign_post = true
				safe = true
				cage = true
				jar = true
				sack = true
				blackboard = true
				globe = true
				rope_knot = true
				bamboo_spikes = true
				goblet = true
				hourglass = true
				item_shelf = true
				doormat = true
				spring_launcher_arm = true
				speaker_block = true
				turn_table = true
				pulley_block = true
				bellows = true
				clock_block = true
				wind_vane = true
				faucet = true
				key_lockable_tile = true
				wall_lantern = true
				hanging_flower_pot = true
				jar_boat = true
				structure_temp = true
				block_generator = true
				timber_frame = true
				flower_box = true
				statue = true
				book_pile = true
				urn = true
				skull_pile = true
				skull_candle = true
				bubble_block = true
				enderman_head = true

			[light_sources.settings.block_entities.pyrotastic]
				fireworks_crate = true

			[light_sources.settings.block_entities.fwaystones]
				waystone = true

			[light_sources.settings.block_entities.betterarcheology]
				archeology_table = true
				villager_fossil = true
				chicken_fossil = true
				sus_block = true
				flee_from = true

			[light_sources.settings.block_entities.biomemakeover]
				poltergeist = true
				lightning_bug_bottle = true
				tapestry = true
				altar = true
				directional_data = true

			[light_sources.settings.block_entities.bitsandchisels]
				bits_block_entity = true

			[light_sources.settings.block_entities.cauldron_dyeing]
				water_cauldron_entity = true

			[light_sources.settings.block_entities.echochest]
				echo_chest = true

			[light_sources.settings.block_entities.forgottengraves]
				grave = true

			[light_sources.settings.block_entities.gardens_of_the_dead]
				sign = true
				hanging_sign = true

			[light_sources.settings.block_entities.just_end_anchor]
				end_anchor = true

			[light_sources.settings.block_entities.snowrealmagic]
				snow = true
				texture_tile = true

			[light_sources.settings.block_entities.regenerations]
				maple = true
				maple_hanging = true

			[light_sources.settings.block_entities.swampier_swamps]
				decaying_kelp = true

			[light_sources.settings.block_entities.davespotioneering]
				compound_brewing_stand = true
				reinforced_cauldron = true
				potion_injector = true

			[light_sources.settings.block_entities.twigs]
				silt_pot = true

			[light_sources.settings.block_entities.urkazmoontools]
				moonsensor_entity = true

			[light_sources.settings.block_entities.wilderwild]
				hanging_tendril = true
				termite_mound = true
				display_lantern = true
				stone_chest = true
				palm_crown = true
				scorched_block = true

			[light_sources.settings.block_entities.windchimes]
				chime = true

			[light_sources.settings.block_entities.wunderreich]
				wunder_kiste_block_entity = true

			[light_sources.settings.block_entities.advancementframes]
				advancement_frame = true

			[light_sources.settings.block_entities.betterlily]
				water_lily_pad = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				wither_skeleton = true
				vex = true
				wandering_trader = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				wither = true
				camel = true
				cobweb = true
				block_display = true
				interaction = true
				item_display = true
				sniffer = true
				text_display = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.endgoblintraders]
				end_goblin_trader = true

			[light_sources.settings.entities.additionaladditions]
				glow_stick = true

			[light_sources.settings.entities.connectiblechains]
				chain_knot = true
				chain_collision = true

			[light_sources.settings.entities.snowyspirit]
				container_entity = true
				sled = true
				gingerbread_golem = true

			[light_sources.settings.entities.sleep_tight]
				bed_entity = true
				dreamer_essence_dummy = true
				bedbug = true

			[light_sources.settings.entities.naturalist]
				rattlesnake = true
				zebra = true
				deer = true
				snail = true
				canary = true
				rhino = true
				firefly = true
				hippo = true
				bluejay = true
				coral_snake = true
				snake = true
				cardinal = true
				lion = true
				vulture = true
				robin = true
				boar = true
				caterpillar = true
				giraffe = true
				butterfly = true
				bear = true
				elephant = true

			[light_sources.settings.entities.capybara]
				capybara = true

			[light_sources.settings.entities.wondrouswilds]
				firefly = true
				woodpecker = true

			[light_sources.settings.entities.goblintraders]
				vein_goblin_trader = true
				goblin_trader = true

			[light_sources.settings.entities.adventurez]
				deer = true
				skeleton_vanguard = true
				thrown_rock = true
				desert_rhino = true
				small_stone_golem = true
				piglin_beast = true
				blaze_guardian = true
				ender_whale = true
				shaman = true
				dragon = true
				stone_golem = true
				iguana = true
				soul_reaper = true
				amethyst_golem = true
				red_fungus = true
				void_cloud = true
				summoner = true
				void_bullet = true
				orc = true
				the_eye = true
				necromancer = true
				fire_breath = true
				void_fragment = true
				brown_fungus = true
				blaze_guardian_shield = true
				nightmare = true
				mammoth = true
				void_shade = true
				tiny_eye = true
				gilded_stone = true
				wither_puppet = true
				enderwarthog = true
				void_shadow = true
				amethyst_shard = true

			[light_sources.settings.entities.immersive_weathering]
				falling_propagule = true
				falling_layer = true
				falling_icicle = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				camel = true
				chest_boat = true
				boat = true
				penguin = true
				coconut_crab = true

			[light_sources.settings.entities.edenring]
				limphium_painting = true
				diskwing = true
				lightning_ray = true

			[light_sources.settings.entities.slimegolem]
				slime_golem = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.decorative_blocks]
				dummy_entity = true

			[light_sources.settings.entities.campanion]
				golden_spear = true
				lawn_chair = true
				flare_thrown = true
				stone_spear = true
				diamond_spear = true
				netherite_spear = true
				wooden_spear = true
				skipping_stone = true
				iron_spear = true
				grappling_hook = true

			[light_sources.settings.entities.sprout]
				bounce_bug = true
				elephant = true
				butterfly = true

			[light_sources.settings.entities.twigs]
				pebble = true

			[light_sources.settings.entities.snuffles]
				snuffle = true

			[light_sources.settings.entities.bettertridents]
				loyal_experience_orb = true
				loyal_item = true

			[light_sources.settings.entities.anx]
				extra_boat = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				desert_creeper = true
				dark_oak_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.progressivebosses]
				area_effect_cloud_3d = true
				larva = true
				wither_minion = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.cave_enhancements]
				dripstone_tortoise = true
				cruncher = true
				thrown_goop = true
				goop = true
				goop_drip = true
				dripstone_pike = true
				harmonic_arrow = true

			[light_sources.settings.entities.immersive_portals]
				nether_portal_new = true
				general_breakable_portal = true
				loading_indicator = true

			[light_sources.settings.entities.charm]
				moobloom = true
				chair = true
				endermite_powder = true
				coral_squid = true

			[light_sources.settings.entities.paradise_lost]
				slider = true
				poison_needle = true
				floating_block = true
				hellenrose = true
				poison_dart = true
				rook = true
				corsican_hare = true
				moa = true

			[light_sources.settings.entities.promenade]
				sunken_skeleton = true
				capybara = true
				duck = true
				lush_creeper = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.oxidized]
				copper_golem = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				falling_ash = true
				falling_lantern = true
				falling_urn = true
				brick_projectile = true
				pearl_marker = true
				falling_sack = true
				red_merchant = true
				bomb = true
				rope_arrow = true

			[light_sources.settings.entities.dawn]
				custom_tnt = true
				flying_block = true

			[light_sources.settings.entities.terraform]
				chest_boat = true
				boat = true

			[light_sources.settings.entities.enchancement]
				ice_shard = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				moobloom = true
				mauler = true
				wildfire = true
				iceologer = true
				tuff_golem = true
				ice_chunk = true
				player_illusion = true
				rascal = true

			[light_sources.settings.entities.pyrotastic]
				fireworks_crate = true

			[light_sources.settings.entities.frame]
				seat = true

			[light_sources.settings.entities.biomemakeover]
				mushroom_trader = true
				glowfish = true
				helmit_crab = true
				lightning_bug = true
				lightning_bug_alternate = true
				dragonfly = true
				scuttler = true
				tumbleweed = true
				rootling = true
				owl = true
				lightning_bottle = true
				blightbat = true
				ghost = true
				cowboy = true
				decayed = true
				toad = true
				tadpole = true
				moth = true
				adjudicator = true
				adjudicator_mimic = true
				stone_golem = true

			[light_sources.settings.entities.swampier_swamps]
				dragonfly = true
				swamp_gas = true

			[light_sources.settings.entities.wilderwild]
				jellyfish = true
				firefly = true
				tumbleweed = true
				ancient_horn_projectile = true
				coconut = true
				chest_bubbler = true
				sculk_spreader = true
				crab = true

			[light_sources.settings.entities.duckling]
				duck = true
				quackling = true
				duck_egg = true

			[light_sources.settings.entities.betterarcheology]
				bombentity = true

			[light_sources.settings.entities.snowrealmagic]
				snow = true

			[light_sources.settings.entities.muffins_slimegolem]
				slime_golem = true

			[light_sources.settings.entities.scribe]
				scribe_boat = true
				scribe_chest_boat = true

			[light_sources.settings.entities.taniwha]
				t_boat = true
				t_chest_boat = true

			[light_sources.settings.entities.endermanoverhaul]
				cave_enderman = true
				end_enderman = true
				end_islands_enderman = true
				nether_wastes_enderman = true
				flower_fields_enderman = true
				savanna_enderman = true
				snowy_enderman = true
				crimson_forest_enderman = true
				mushroom_fields_enderman = true

			[light_sources.settings.entities.sihywtcamd]
				cobweb = true

			[light_sources.settings.entities.natures_spirit]
				larch_boat = true

			[light_sources.settings.entities.gipples_galore]
				gipple = true

			[light_sources.settings.entities.clutter]
				echofin = true
				ember_tortoise = true

			[light_sources.settings.entities.goodending]
				woodpecker = true

